apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: i2scim-svc
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
      labels:
        app.kubernetes.io/name: i2scim

    spec:
      selector:
        app: i2scim
      ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080
      externalIPs:
        - 192.168.1.104
        - 192.168.1.105
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: i2scim
    spec:
      serviceName: i2scim-svc
      replicas: 2
      selector:
        matchLabels:
          app: i2scim
      template:
        metadata:
          labels:
            app: i2scim
        spec:
          containers:
            - name: i2scim
              imagePullPolicy: Always
              image: independentid/i2scim-memory:0.5.0-Alpha
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /q/health/live
                  port: 80
                  scheme: HTTP
                initialDelaySeconds: 0
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 10
              ports:
                - containerPort: 80
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /q/health/ready
                  port: 80
                  scheme: HTTP
                initialDelaySeconds: 0
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 10
              env:
                - name: scim.prov.providerClass
                  value: com.independentid.scim.backend.memory.MemoryProvider
                - name: scim.prov.memory.dir
                  value: /scim/scimdata
                - name: scim.prov.memory.file
                  value: scimdb.json
                - name: scim.prov.mongo.indexes
                  value: User:userName,User:emails.value,Group:displayName
                - name: scim.event.enable
                  value: "false"
                - name: scim.security.enable
                  value: "true"
                - name: scim.security.root.enable
                  value: "true"
                - name: scim.security.root.username
                  valueFrom:
                    secretKeyRef:
                      name: rootSecret
                      key: username
                - name: scim.security.root.password
                  valueFrom:
                    secretKeyRef:
                      name: rootSecret
                      key: password
              volumeMounts:
                - mountPath: /scim
                  name: i2scim-pvc
          imagePullSecrets:
            - name: regcred
      volumeClaimTemplates:
        - metadata:
            name: i2scim-pvc
          spec:
            selector:
              matchLabels:
                app: i2scim
            storageClassName: nfs
            accessModes: [ ReadWriteOnce ]
            resources:
              requests:
                storage: 50Gi