apiVersion: v1
kind: Secret
metadata:
  name: i2scim-root
  namespace: scim-mem
type: Opaque
data:
  scim.security.root.username: YWRtaW4=
  scim.security.root.password: YWRtaW4=
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: scim-mem
  name: i2scim-mem-config
data:
  - name: scim.event.enable
    value: "false"
  - name: scim.prov.providerClass
    value: com.independentid.scim.backend.memory.MemoryProvider
  - name: scim.prov.memory.dir
    value: "/scim/data"
  - name: scim.prov.memory.file
    value: "scimdb.json"
  - name: scim.prov.memory.maxbackups
    value: "10"
  - name: scim.prov.memory.backup.mins"
    value: "60"
    # Indicates the attributes to be indexed
  - name: scim.prov.memory.indexes
    value: User:userName,User:emails.value,Group:displayName

    # Security Configuration
  - name: scim.security.enable
    value: "true"
    # Locations of the acis.json file to use
  - name: scim.security.acis
    value: "/schema/acis.json"
  - name: scim.security.root.enable
    value: "true"
    # When basic is enabled, i2scim will attempt to process HTTP Basic Auth against User resources
    # located in the Memory provider database.
  - name: scim.security.authen.basic
    value: "true"

    # Configuration for JWT authentication
  - name: scim.security.authen.jwt
    value: "false"

    # The JWT claim used to match RBAC scopes used in acis processing
  - name: scim.security.authen.jwt.claim.scope
    value: "scope"

    # See: Quarkus Using JWT RBAC for configuration details
    # https://quarkus.io/guides/security-jwt
  - name: quarkus.smallrye-jwt.enabled
    value: "true"
  - name: smallrye.jwt.verify.key.location
    value: "/certs/jwks-certs.json"
  - name: smallrye.jwt.always-check-authorization
    value: "true"
  - name: mp.jwt.verify.issuer
    value: "http://10.1.10.109:8180/auth/realms/dev"
---