apiVersion: v1
kind: ConfigMap
metadata:
  name: i2scim-configmap
  namespace: default
data:
  mp.jwt.verify.issuer: http://10.1.10.109:8180/auth/realms/dev
  quarkus.application.name: i2scim
  quarkus.container-image.builder: docker
  quarkus.container-image.group: independentid
  quarkus.container-image.name: i2scim
  quarkus.container-image.tag: "0.1"
  quarkus.http.access-log.base-file-name: scim-access
  quarkus.http.access-log.enabled: "true"
  quarkus.http.access-log.log-directory: /Users/pjdhunt/scim/logs
  quarkus.http.access-log.log-to-file: "true"
  quarkus.kubernetes-config.config-maps: i2scim
  quarkus.log.min-level: FINE
  quarkus.package.type: fast-jar
  quarkus.smallrye-jwt.enabled: "true"
  quarkus.smallrye-metrics.jaxrs.enabled: "true"
  quarkus.smallrye-metrics.path: /metrics
  scim.bulk.max.errors: "5"
  scim.bulk.max.ops: "1000"
  scim.coreSchema.path: classpath:/schema/scimCommonSchema.json
  scim.event.enable: "true"
  scim.json.pretty: "true"
  scim.prov.memory.backup.mins: "60"
  scim.prov.memory.maxbackups: "10"
  scim.prov.memory.persist.dir: ./scimdata
  scim.prov.memory.persist.file: scimdb.json
  scim.prov.memory: indexes=User:userName,User:emails.value,Group:displayName
  scim.prov.persist.schema: "true"
  scim.prov.providerClass: com.independentid.scim.backend.memory.MemoryProvider
  scim.query.max.resultsize: "1000"
  scim.resourcetype.path: classpath:/schema/resourceTypes.json
  scim.schema.path: classpath:/schema/scimSchema.json
  scim.security.acis: /schema/acis.json
  scim.security.authen.basic: "false"
  scim.security.authen.jwt: "false"
  scim.security.authen.jwt.claim.scope: scope
  scim.security.enable: "true"
  scim.security.root.enable: "true"
  scim.security.root.password: admin
  scim.security.root.username: admin
  scim.thread.count: "5"
  smallrye.jwt.always-check-authorization: "true"
  smallrye.jwt.verify.key.location: /certs/jwks-certs.json
---

